// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU0i3v4MdSY7vrnzwlJJwhux7yntpbHW8',
    appId: '1:733958712984:web:cd2dbd451df680ac106aed',
    messagingSenderId: '733958712984',
    projectId: 'cruncch-8da0d',
    authDomain: 'cruncch-8da0d.firebaseapp.com',
    storageBucket: 'cruncch-8da0d.firebasestorage.app',
    measurementId: 'G-3JG2LZ0ZK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Ntlm8R17M8VPS5WWd_bcqnd6kn5Qv8w',
    appId: '1:733958712984:android:81b8fe51143b0e6a106aed',
    messagingSenderId: '733958712984',
    projectId: 'cruncch-8da0d',
    storageBucket: 'cruncch-8da0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoEuhngdKOqyZuf2efZu73H6zAOdd9YhU',
    appId: '1:733958712984:ios:80435187a00bd09f106aed',
    messagingSenderId: '733958712984',
    projectId: 'cruncch-8da0d',
    storageBucket: 'cruncch-8da0d.firebasestorage.app',
    iosBundleId: 'com.example.craveapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoEuhngdKOqyZuf2efZu73H6zAOdd9YhU',
    appId: '1:733958712984:ios:80435187a00bd09f106aed',
    messagingSenderId: '733958712984',
    projectId: 'cruncch-8da0d',
    storageBucket: 'cruncch-8da0d.firebasestorage.app',
    iosBundleId: 'com.example.craveapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU0i3v4MdSY7vrnzwlJJwhux7yntpbHW8',
    appId: '1:733958712984:web:de2f092a2be6fd6e106aed',
    messagingSenderId: '733958712984',
    projectId: 'cruncch-8da0d',
    authDomain: 'cruncch-8da0d.firebaseapp.com',
    storageBucket: 'cruncch-8da0d.firebasestorage.app',
    measurementId: 'G-6MWX2JWNEF',
  );
}
